### ISSUE TITLE
Example of how to use -var argument

### ISSUE THREAD

**Issue by bencodeorg** [snowplow/sql-runner#122]
Hello sql-runner! This may be a bit of a basic question, but I can find no documentation of the appropriate syntax to use when referncing an argument passed in via `-var` (I don't really know anything about Go, this question is probably not relevant for those who do). 

I see some discussion of supporting multiple arguments (#120), but can't seem to find an example of how to simply pass in a single value? Specifically, I'd like to be able to pass a password and reference it in my playbook. 

Also, thank you for this tool! We're hoping to using it at Code.org to manage some of our analytics processes.

**Comment by BenFradet** [comment]
You can specify it as `-var key=value`, it should be specified when you run `./sql-runner -help`: https://github.com/snowplow/sql-runner/wiki/Guide-for-devops

As of the latest release it's only possible to pass one. However, if you're building from develop you can pass multiple variables.

Next time, please, ask for support on [our forum](https://discourse.snowplowanalytics.com/) so that everyone can benefit from your question.

>Also, thank you for this tool! We're hoping to using it at Code.org to manage some of our analytics processes.

Thanks :+1:

**Comment by bencodeorg** [comment]
Thanks Ben! Apologies for not using the forum, moving further discussion here:

https://discourse.snowplowanalytics.com/t/accessing-command-line-arguments-in-playbook/1901
