### ISSUE TITLE
Add an aws_creds function for COPY commands

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/sql-runner#36]

**Comment by andrioni** [comment]
:+1:
Another useful thing would be the option to get role-based credentials whenever available, and [it seems the Golang SDK already has this implemented](https://github.com/aws/aws-sdk-go/wiki/Getting-Started-Credentials#using-profiles-with-the-sdk).

**Comment by alexanderdean** [comment]
Yes that would be nice...

**Comment by andrioni** [comment]
Any ideas on how do you plan on doing it? I think I might be able to contribute something towards it in the next few days, since I'm gonna need it too.

The easiest way I see is to use the Golang SDK (which automatically gives us the support to reading the credentials from profiles, environment variables and roles), and then inject them as predefined variables (`aws_access_key_id` and `aws_secret_access_key`?) inside the playbook. Any objections to this approach?

**Comment by alexanderdean** [comment]
Using the Golang SDK sounds good. I think the two options are:

> inject them as predefined variables (aws_access_key_id and aws_secret_access_key?) inside the playbook

or

2. Create a template function `aws_access_credentials` which generates a string of the format:

    'aws_access_key_id=<access-key-id>;aws_secret_access_key=<secret-access-key>'

This is because the only places I can think these creds would be useful are in COPY and UNLOAD statements, which use the above credentials syntax...

**Comment by andrioni** [comment]
Yes, indeed, and it avoids horribly overextending the meaning and creation methods of variables.

**Comment by alexanderdean** [comment]
Cool!

**Comment by alexanderdean** [comment]
Duplicate of #39
